os:
  - windows
  - linux

language: node_js

node_js:
  - "10"

cache:
  npm: true

addons:
  apt:
    sources:
      - deadsnakes

    packages:
      - python3-venv
      - python3.7
      - python3.7-venv
      - python3.6-venv
      - python3.7-dev
  
install:
  if [ $TRAVIS_OS_NAME == "windows" ]; then
  choco install python --version 3.7.5;
  fi;

script:
  - npm install
  - npm test
  - npm run lint
