os:
  - windows
  - linux

language: node_js

node_js:
  - "10"

cache:
  npm: true

env:
  - TRAVIS_TASK="build" NODESTYLE_SKIP_PREPARE=false
  - TRAVIS_TASK="lint" NODESTYLE_SKIP_PREPARE=true

before_install:
  source ./.travis/before_install.sh

script:
  source ./.travis/script.sh
